name: CI/CD for Django Project

on:
  push:
    branches:
      - origin
  pull_request:
    branches:
      - origin

jobs:
  lint-and-test:
    name: Linting and Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
          pip install coverage
          pip install django-coverage-plugin

      - name: Run Linting
        run: |
          flake8 .

      - name: Run Tests
        run: |
          python manage.py test

      - name: Collect Test Coverage
        run: |
          coverage run --source='.' manage.py test
          coverage report -m

  build-and-deploy:
    name: Build and Deploy Test Report
    runs-on: ubuntu-latest
    needs: lint-and-test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage
          pip install django-coverage-plugin

      - name: Generate Test Report
        run: |
          coverage run --source='.' manage.py test
          coverage html -i

      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: htmlcov/
